config/routes.rb
Rails.application.routes.draw do
  root "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:create, :destroy]
  end
  # delete "doses/:id" => "doses#destroy"
  resources :ingredients, only: [:show]
  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail,
    message: "should be unique" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :restrict_with_exception
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
      #cocktail_path = @cocktail (shortcut)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to ncocktails_path, notice: 'Cocktail was successfully deleted'
  end

private

  def cocktails_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:create]

  def create
    # @dose = @cocktail.doses.build(dose_params) -> pareil que les deux lignes suivantes
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
      if @dose.save
        redirect_to cocktail_path(@cocktail)
      else
        render "cocktails/show"
      end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

# ------------------------
# SI PAGE DIFFERENTE POUR LA DOSE
# ------------------------
# def new
# end
# ------------------------
# > html :
# simple_form_for [@cocktail, Dose.new] do |f|
# f.input :description
# f.input :ingredient_id, collection: Ingredient.all
# f.submit
# end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

def show
  @ingredient = Ingredient.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
<%= f.input :name, placeholder: "Enter a cocktail name" %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<h1> Cocktails of the house </h1>
<p> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --</p>
<div class="container">
<%= link_to "Add a new cocktail", new_cocktail_path %>
<p> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --</p>

<% @cocktails.each do |cocktail| %>
<h3> <%= link_to cocktail.name, cocktail_path(cocktail) %> </h3>
<ul>
<li> <%= cl_image_tag(cocktail.photo,
      width: 300, height: 300, crop: :fill) %> </li>
<p> -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --</p>
<li> <%= link_to "delete", cocktail_path(cocktail), method: :delete %> </li>
</ul>

<% end %>
</div>

app/views/cocktails/new.html.erb
<h1> Brand new cocktail of the house </h1>

<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1> <%= @cocktail.name %> </h1>

<%= cl_image_tag(@cocktail.photo,
      width: 400, height: 300, crop: :fill) %>

<ul>
<% @cocktail.doses.each do |dose| %>
  <li>  <%= dose.description %> de <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> </li>
<li> <%= link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete %> </li>
<% end %>
</ul>

<h3> Add an ingredient </h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <% if @dose.errors.any? %>
    <% @dose.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
<%= f.input :description, placeholder: "Enter a dose" %>
<%= f.collection_select :ingredient_id, Ingredient.order(:name), :id, :name, prompt: "Choose one" %>
<%= f.submit "Add dose" %>
<% end %>

<%= link_to 'Back', cocktails_path %>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.name %> </h1>
<h3> Voici les cocktails qui contiennent <%= @ingredient.name %></h3>
<ul> <% @ingredient.cocktails.each do |cocktail| %>
  <li> <%= cocktail.name %> </li>
  <%= cl_image_tag cocktail.photo, height: 100, width: 150, crop: :fill %>
  <% end %>
</ul>

<%= link_to 'Back', cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>